
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartProcessConfigCategory : Singleton<StartProcessConfigCategory>, IConfig
    {
        private readonly Dictionary<int, StartProcessConfig> _dataMap;
        private readonly List<StartProcessConfig> _dataList;

        public StartProcessConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, StartProcessConfig>();
            _dataList = new List<StartProcessConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                StartProcessConfig _v;
                _v = StartProcessConfig.DeserializeStartProcessConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, StartProcessConfig> DataMap => _dataMap;
        public List<StartProcessConfig> DataList => _dataList;

        public StartProcessConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public StartProcessConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
