
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class StartSceneConfig : BeanBase
    {
        public StartSceneConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Process = _buf.ReadInt();
            Zone = _buf.ReadInt();
            SceneType = _buf.ReadString();
            Name = _buf.ReadString();
            Port = _buf.ReadInt();

            PostInit();
        }

        public static StartSceneConfig DeserializeStartSceneConfig(ByteBuf _buf)
        {
            return new StartSceneConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 所属进程
        /// </summary>
        public readonly int Process;

        /// <summary>
        /// 所属区
        /// </summary>
        public readonly int Zone;

        /// <summary>
        /// 类型
        /// </summary>
        public readonly string SceneType;

        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 外网端口
        /// </summary>
        public readonly int Port;


        public const int __ID__ = 1499456844;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Process:" + Process + ","
            + "Zone:" + Zone + ","
            + "SceneType:" + SceneType + ","
            + "Name:" + Name + ","
            + "Port:" + Port + ","
            + "}";
        }

        partial void PostInit();
    }
}
