
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StartSceneConfigCategory : Singleton<StartSceneConfigCategory>, IConfig
    {
        private readonly Dictionary<int, StartSceneConfig> _dataMap;
        private readonly List<StartSceneConfig> _dataList;

        public StartSceneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, StartSceneConfig>();
            _dataList = new List<StartSceneConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                StartSceneConfig _v;
                _v = StartSceneConfig.DeserializeStartSceneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, StartSceneConfig> DataMap => _dataMap;
        public List<StartSceneConfig> DataList => _dataList;

        public StartSceneConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public StartSceneConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
