
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sirenix.OdinInspector;

namespace ET
{
    public enum EQuality
    {
        /// <summary>
        /// 最差品质
        /// </summary>
        [LabelText("白")]
        WHITE = 1,
        /// <summary>
        /// 绿色
        /// </summary>
        [LabelText("绿")]
        GREEN = 2,
        /// <summary>
        /// 蓝色的
        /// </summary>
        [LabelText("蓝")]
        BLUE = 3,
        /// <summary>
        /// 紫色的
        /// </summary>
        [LabelText("紫")]
        PURPLE = 4,
        /// <summary>
        /// 橙色
        /// </summary>
        [LabelText("橙")]
        ORANGE = 5,
        /// <summary>
        /// 最高品质
        /// </summary>
        [LabelText("红")]
        RED = 6,
    }
}
