
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum EQuality
    {
        /// <summary>
        /// 最差品质
        /// </summary>
        WHITE = 1,

        /// <summary>
        /// 绿色
        /// </summary>
        GREEN = 2,

        /// <summary>
        /// 蓝色的
        /// </summary>
        BLUE = 3,

        /// <summary>
        /// 紫色的
        /// </summary>
        PURPLE = 4,

        /// <summary>
        /// 橙色
        /// </summary>
        ORANGE = 5,

        /// <summary>
        /// 最高品质
        /// </summary>
        RED = 6,

    }
}
