
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class UnitConfigCategory : Singleton<UnitConfigCategory>, IConfig
    {
        private readonly Dictionary<int, UnitConfig> _dataMap;
        private readonly List<UnitConfig> _dataList;

        public UnitConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, UnitConfig>();
            _dataList = new List<UnitConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                UnitConfig _v;
                _v = UnitConfig.DeserializeUnitConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, UnitConfig> DataMap => _dataMap;
        public List<UnitConfig> DataList => _dataList;

        public UnitConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public UnitConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
